version: "3"

services:
  core_web:
    image: nginx:stable-alpine
    container_name: core_web
    restart: unless-stopped
    tty: true
    ports:
      - "18001:80"
      - "18011:443"
    volumes:
      - ./src/core:/var/www/dorcas-business-core
      - ./web/core_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - core_php
    extra_hosts:
      - "business:192.168.8.100"
    networks:
      - business

  core_php:
    image: dorcashub/dorcas-business-base:latest
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: core_php
      SERVICE_TAGS: dev
    working_dir: /var/www/dorcas-business-core
    env_file: ./app/env_core
    container_name: core_php
    volumes:
#      - ./src/core:/var/www
      - ./app/env_core:/var/www/dorcas-business-core/.env
      - ./app/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - dorcas_sql
      - dorcas_redis
    networks:
      - business

  hub_web:
    image: nginx:stable-alpine
    container_name: hub_web
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "18022:443"
    volumes:
      - ./src/hub:/var/www
      - ./web/hub_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hub_php
      - core_web
    networks:
      - business

  hub_php:
    # image: dorcashub/docker-business-hub:latest
    image: dorcashub/dorcas-business-hub:latest
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: hub_php
      SERVICE_TAGS: dev
    working_dir: /var/www
    env_file: ./app/env_hub
    container_name: hub_php
    volumes:
      #- ./src:/var/www
      - ./app/env_hub:/var/www/.env
      - ./app/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - dorcas_hub_sql
      - dorcas_redis
      - dorcas_smtp
    # command: "php artisan storage:link"
    networks:
      - business

  dorcas_sql:
    image: mysql:5.7
    container_name: dorcas_sql
    restart: unless-stopped
    # tty: true
    ports:
      - "18008:3306"
    volumes:
      - databases:/var/lib/mysql
      - ./mysql/dorcas_hub.sql:/docker-entrypoint-initdb.d/dorcas_hub.sql
      - ./mysql/dorcas.sql:/docker-entrypoint-initdb.d/dorcas.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_ROOT_USER=homestead
      - MYSQL_DATABASE=dorcas
      # - MYSQL_PASSWORD=root
      - SERVICE_NAME=dorcas_core_sql

    networks:
      - business

  dorcas_hub_sql:
    image: mysql:5.7
    container_name: dorcas_hub_sql
    restart: unless-stopped
    # tty: true
    ports:
      - "3302:3306"
    volumes:
      - hub_database:/var/lib/mysql
      - ./mysql/dorcas_hub.sql:/docker-entrypoint-initdb.d/dorcas_hub.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_ROOT_USER=user
      - MYSQL_DATABASE=dorcas_hub
      # - MYSQL_USER=user
      # - MYSQL_PASSWORD=password
      - SERVICE_NAME=dorcas_hub_sql

    networks:
      - business

  dorcas_redis:
    image: redis:5.0-alpine
    container_name: dorcas_redis
    restart: unless-stopped
    tty: true
    ports:
      - "8002:6379"
    volumes:
      #      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    networks:
      - business

  dorcas_smtp:
    image: mailhog/mailhog:latest
    container_name: dorcas_smtp
    restart: unless-stopped
    tty: true
    ports:
      - "18125:1025"
      - "18825:8025"
    networks:
      - business

#Volumes
volumes:
  databases:
    driver: local
  hub_database:
    driver: local

networks:
  business:
    driver: bridge
