version: "3"

services:
  business_proxy:
    container_name: "${SERVICE_PROXY_NAME}"
    image: ${SERVICE_PROXY_IMAGE}
    ports:
      - "${SERVICE_PROXY_PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - dorcas

  business_core_php:
    container_name: "${SERVICE_CORE_PHP_NAME}"
    image: "${SERVICE_CORE_PHP_IMAGE}"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: "${SERVICE_CORE_PHP_NAME}"
      SERVICE_TAGS: dev
    working_dir: "${SERVICE_CORE_PHP_WORKING_DIR}"
    env_file: ./app/env_core_production
    volumes:
      #      - ./src/core:/var/www
      - ./app/env_core_production:/var/www/dorcas-business-core/.env
      - ./app/local.ini:/usr/local/etc/php/conf.d/local.ini
      #- ${PWD}/web/cors_settings.conf:/etc/nginx/cors_settings.conf
    depends_on:
      - business_mysql
      - business_redis
      - business_smtp
    networks:
      - dorcas

  business_core_web:
    container_name: business_core_web
    build:
      context: ./nginx/core
    restart: unless-stopped
    tty: true
    ports:
      - "${SERVICE_CORE_WEB_PORT}:80"
    #volumes:
    # - ${PWD}/nginx/entrypoint-core.sh:/entrypoint.sh
    #- ${PWD}/web/cors_settings.conf:/etc/nginx/cors_settings.conf
    depends_on:
      - business_core_php
    networks:
      - dorcas
    environment:
      - VIRTUAL_HOST=core.dorcashub.test
      - SERVICE_CORE_PHP_NAME=${SERVICE_CORE_PHP_NAME}

  business_hub_php:
    container_name: business_hub_php
    image: dorcashub/dorcas-hub-business:dev
    #build:
    #  context: ../../Hub/hub-business
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: business_hub_php
      SERVICE_TAGS: dev
    working_dir: /var/www/dorcas-business-hub
    env_file: ./app/env_hub_production
    volumes:
      #  - ../../Hub/hub-business:/var/www
      - ./app/env_hub_production:/var/www/dorcas-business-hub/.env
      - ./app/local.ini:/usr/local/etc/php/conf.d/local.ini
      #- ${PWD}/web/cors_settings.conf:/etc/nginx/cors_settings.conf
    #command: "composer install"
    depends_on:
      - business_mysql
      - business_redis
    # - dorcas_business_smtp
    # command: "php artisan storage:link"
    networks:
      - dorcas

  business_hub_web:
    container_name: business_hub_web
    build:
      context: ./nginx/hub
    restart: unless-stopped
    tty: true
    ports:
      - "${SERVICE_HUB_WEB_PORT}:80"
    #volumes:
    # - ${PWD}/nginx/entrypoint-hub.sh:/entrypoint.sh
    #- ${PWD}/web/cors_settings.conf:/etc/nginx/cors_settings.conf
    depends_on:
      - business_hub_php
      - business_core_web
    networks:
      - dorcas
    environment:
      - VIRTUAL_HOST=dorcashub.test,store.dorcashub.test,blog.dorcashub.test
      - SERVICE_HUB_PHP_NAME=${SERVICE_HUB_PHP_NAME}

  business_mysql:
    container_name: business_mysql
    #image: mysql:5.7
    build:
      context: ./mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    # tty: true
    ports:
      - "${SERVICE_MYSQL_PORT}:3306"
    volumes:
      - dorcas_business_databases:/var/lib/mysql
      #- ${PWD}/mysql/core.sql:/docker-entrypoint-initdb.d/core.sql
      #- ${PWD}/mysql/hub.sql:/docker-entrypoint-initdb.d/hub.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${SERVICE_MYSQL_PASSWORD}
      #- MYSQL_DATABASE=dorcas
      - VIRTUAL_HOST=mysql.dorcashub.test
      - SERVICE_NAME=business_mysql
    networks:
      - dorcas

  business_redis:
    container_name: business_redis
    image: redis:5.0-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${SERVICE_REDIS_PORT}:6379"
    volumes:
      #  - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    networks:
      - dorcas
    environment:
      - VIRTUAL_HOST=redis.dorcashub.test

  business_smtp:
    container_name: business_smtp
    image: mailhog/mailhog:latest
    restart: unless-stopped
    tty: true
    ports:
      - "${SERVICE_SMTP_PORT}:1025"
      - "18825:8025"
    networks:
      - dorcas
    environment:
      - VIRTUAL_HOST=smtp.dorcashub.test

volumes:
  dorcas_business_databases:
    driver: local

networks:
  dorcas:
    driver: bridge
