version: "3"

services:
  business_hub_php:
    container_name: "${SERVICE_HUB_PHP_NAME}_development"
    build:
    context: ./app/Dockerfile.hub

  business_core_reloader:
    container_name: "${SERVICE_RELOADER_NAME}_hub"
    image: "${SERVICE_RELOADER_IMAGE}"
    privileged: true
    environment:
      - RELOAD_DELAY=1.5
      - RELOAD_CONTAINER=${SERVICE_HUB_PHP_NAME}_development
      #- RELOAD_DIR=
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${SERVICE_HUB_PHP_SRC_DIR}:${SERVICE_HUB_PHP_WORKING_DIR}"
