version: "3"

services:
  business_hub_php_development:
    container_name: "${SERVICE_HUB_PHP_NAME}"
    build:
      context: "${SERVICE_HUB_PHP_APP_DIR}"
      dockerfile: "Dockerfile.hub"

  business_reloader_development_hub:
    container_name: "${SERVICE_RELOADER_NAME}_hub"
    image: "${SERVICE_RELOADER_IMAGE}"
    privileged: true
    environment:
      - RELOAD_DELAY=60
      - RESTART_TIMEOUT=10
      - RELOAD_CONTAINER=${SERVICE_HUB_PHP_NAME}
      - RELOAD_DIR=${SERVICE_HUB_PHP_WORKING_DIR}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${SERVICE_HUB_PHP_SRC_DIR}:${SERVICE_HUB_PHP_WORKING_DIR}"
