version: "3"

services:
  business_core_php_development:
    container_name: "${SERVICE_CORE_PHP_NAME}"
    build:
      context: "${SERVICE_CORE_PHP_APP_DIR}"
      dockerfile: "Dockerfile.core"

  business_reloader_development_core:
    container_name: "${SERVICE_RELOADER_NAME}_core"
    image: "${SERVICE_RELOADER_IMAGE}"
    privileged: true
    environment:
      - RELOAD_DELAY=60
      - RESTART_TIMEOUT=10
      - RELOAD_CONTAINER=${SERVICE_CORE_PHP_NAME}
      - RELOAD_DIR=${SERVICE_CORE_PHP_WORKING_DIR}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${SERVICE_CORE_PHP_SRC_DIR}:${SERVICE_CORE_PHP_WORKING_DIR}"
